sudo: required
services:
  - docker
  
before_install:
  - docker build -t suryatheja1991/docker-react -f Dockerfile.dev .
  
script:
  - docker run suryatheja1991/docker-react npm run test -- --coverage
  
  